---
- name: Check if {{ export_dir }} is mountpoint
  command: mountpoint -q {{ export_dir }} # -q is --quiet option
  register: volume_stat
  failed_when: False
  changed_when: False

# <regex>.rc contains the exit code of command line module (e.g command)
- debug:
    msg: 'ERROR: mountpoint -q {{ export_dir }} returned non-zero EXIT CODE: {{ export_dir }} is not a mountpoint.'
  when: volume_stat.rc != 0

- name: 'Try to mount /dev/vdb to {{ export_dir }}'
  command:  'mount /dev/vdb {{ export_dir }}'
  become_user: root
  become_method: sudo
  when: volume_stat.rc != 0
  register: mount_stat

- fail:
    msg: 'Unable to mount /dev/vdb to {{ export_dir }}'
  when:
    - volume_stat.rc != 0
    - mount_stat.rc != 0 
