---
#______________________________________
# Configure {{ galaxy_user }} .bashrc to show instance status at startup

- name: 'Copy check_instance script'
  template:
    src: 'check_instance.sh.j2'
    dest: '{{ custom_utils_path }}/check_instance'
    mode: a+x

- name: Add check instance script to bashrc
  lineinfile:
    dest: '/home/{{ galaxy_user }}/.bashrc'
    line: '{{ custom_utils_path }}/check_instance'
    state: present
