---
# Recipe to encrypt external volume

#______________________________________
# CentOS 7

- name: '[EL] Install packages'
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - cryptsetup-luks
    - pv
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

#______________________________________
# Ubuntu

- name: '[Ubuntu] Install packages'
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - cryptsetup
    - pv
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

#______________________________________
# LUKSformat volume

- name: Clone fast_luks script
  git:
    repo: 'https://github.com/Laniakea-elixir-it/fast-luks.git'
    dest: '{{ custom_utils_path }}'
    version: 'devel'

- name: Copy kickout scripts
  template:
    src: 'kickout.j2'
    dest: '{{ custom_utils_path }}/kickout'
    mode: a+x

- name: Add luks scripts
  lineinfile:
    dest: '{{ item.dest }}'
    line: '{{ item.command }}'
    state: present
  with_items:
    - { dest: '/home/{{ galaxy_user }}/.bashrc', command: 'sudo {{ custom_utils_path }}/fast-luks.sh' }
    - { dest: '/home/{{ galaxy_user }}/.bashrc', command: 'source {{ custom_utils_path }}/kickout' }
  when: not paranoid_mode|bool

- name: Add luks scripts
  lineinfile:
    dest: '{{ item.dest }}'
    line: '{{ item.command }}'
    state: present
  with_items:
    - { dest: '/home/{{ galaxy_user }}/.bashrc', command: 'sudo {{ custom_utils_path }}/fast-luks.sh --paranoid-mode' }
    - { dest: '/home/{{ galaxy_user }}/.bashrc', command: 'source {{ custom_utils_path }}/kickout' }
  when: paranoid_mode|bool

# check if /export is mountpoint before LUKS encryption
- include: check_mountpoint_in.yml

# send a mail to the administrator: Notification simulation
- include: sendmail.yml

- name: Wait for fast-luks start (pidfile creation)
  wait_for:
    path: /var/run/fast_luks/fast-luks-encryption.pid
    timeout: '{{ wait_timeout }}'

- name: Wait for fast-luks finish (pidfile deletion)
  wait_for:
    path: /var/run/fast_luks/fast-luks-volume-setup.pid
    state: absent
    timeout: '{{ wait_timeout }}'

- name: 'Wait for LUKS success file: {{ luks_success_file }}'
  wait_for:
    path: '{{ luks_success_file }}' # FIXED in fast-luks script
    timeout: '{{ wait_timeout }}'
    search_regex: "LUKS encryption completed."

- name: 'Wait for volume setup success file: {{ volume_setup_success_file }}'
  wait_for:
    path: '{{ volume_setup_success_file }}' # FIXED in fast-luks script
    timeout: '{{ wait_timeout }}'
    search_regex: "LUKS encryption completed."

- name: 'Check {{ luks_config_file }}. If not present something went wrong'
  wait_for:
    path: '{{ luks_config_file }}'
    state: present

# After LUKS procedure, we need to set export_dir permissions and recreate tool_deps directory, since it has been deleted.
- name: 'Set {{ export_dir }} permissions and recreate {{ tool_deps_path }} directory'
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ galaxy_user }}'
    group: '{{ galaxy_user }}'
  with_items:
    - '{{ export_dir }}'
    - '{{ tool_deps_path }}'
  become_user: root
  become_method: sudo

# check if {{ export_dir }} is a mountpoint after LUKS encryption
- include: check_mountpoint_out.yml

- name: Remove fast_luks scripts automatism from bashrc
  lineinfile:
    dest: '{{ item.dest }}'
    line: '{{ item.command }}'
    state: absent
  with_items:
    - { dest: '/home/{{ galaxy_user }}/.bashrc', command: 'sudo {{ galaxy_custom_script_path }}/fast-luks' }
    - { dest: '/home/{{ galaxy_user }}/.bashrc', command: 'source {{ galaxy_custom_script_path }}/kickout' }
