---
# Main tasks file for indigo-dc.galaxycloud
# Deploy a Galaxy server

# Users rules
- include: user.yml

# Install Galaxy dependencies
- include: prerequisites.yml

# Use Onedata space as default storage
- include: onedata.yml
  when: isolation_level == 'onedata'
  become_user: '{{ galaxy_user }}'
  become: true

# LUKS format external volume
- include: luks.yml
  when: isolation_level == 'encryption'
  become_user: '{{ galaxy_user }}'
  become: true
