---
# Main tasks file for indigo-dc.galaxycloud-os
# Advanced storage configuration

# Create directories
- include: path.yml

# Users rules
- include: user.yml

# Install Galaxy dependencies
- include: prerequisites.yml

# Use Onedata space as default storage
- include: onedata.yml
  when: os_storage == 'onedata'
  become_user: '{{ galaxy_user }}'
  become: true

# LUKS format external volume
- include: luks.yml
  when: os_storage == 'encryption'
  become_user: '{{ galaxy_user }}'
  become: true
