---
- name: Copy onedatactl.py script
  template:
    src: 'onedatactl.py.j2'
    dest: '/usr/local/bin/onedatactl'
    mode: 'a+x'
  become_user: root
  become_method: sudo

- name: Copy onedatactl.ini file
  template:
    src: 'onedatactl.ini.j2'
    dest: '{{ onedatactl_config_file }}'
  become_user: root
  become_method: sudo

- name: Configure onedatactl configuration file
  ini_file:
    dest: '{{ onedatactl_config_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: 'userdata', option: 'mountpoint', value: '{{ export_dir }}' }
    - { section: 'userdata', option: 'provider', value: '{{ userdata_provider }}' }
    - { section: 'userdata', option: 'token', value: '{{ userdata_token }}' }
  become_user: root
  become_method: sudo

- name: Mount Onedata Galaxy Data space
  shell: 'oneclient -H {{ userdata_provider }} -t {{ userdata_token }} {{ export_dir }} --insecure'
