---
- name: Mount Onedata Galaxy Data space
  shell: 'oneclient -H {{ userdata_provider }} -t {{ userdata_token }} {{ onedata_dir }} --insecure -o nonempty'

- name: Copy onedatactl.ini file
  template:
    src: 'onedatactl.ini.j2'
    dest: '{{ onedatactl_config_file }}'
  become_user: root
  become_method: sudo

- name: Configure onedatactl configuration file
  ini_file:
    dest: '{{ onedatactl_config_file }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: 'userdata', option: 'mountpoint', value: '{{ onedata_dir }}' }
    - { section: 'userdata', option: 'provider', value: '{{ userdata_provider }}' }
    - { section: 'userdata', option: 'token', value: '{{ userdata_token }}' }
    - { section: 'userdata', option: 'insecure', value: '{{ insecure }}' }
    - { section: 'userdata', option: 'nonempty', value: '{{ nonempty }}' }
    - { section: 'userdata', option: 'uid', value: '{{ uid }}' }
    - { section: 'userdata', option: 'gid', value: '{{ gid }}' }
  become_user: root
  become_method: sudo

#- name: Create {{ tool_deps_path }} directory
#  file:
#    path: '{{ tool_deps_path }}'
#    state: directory
  #  owner: '{{ galaxy_user }}'
  #  group: '{{ galaxy_user }}'
  #become_user: root
  #become_method: sudo
