---
# Create directories

#______________________________________
# Common path configuration
#
# Mountpoint: /export
# Tool dependency dir: /export/tool_deps
# Conda dir: /export/_conda
# Job working dir: /export/job_work_dir
# Galaxy database dir (galaxy_db_dir): /export/galaxy/database
# Galaxy log: /var/log/galaxy
# Galxy custom configuration path: /etc/galaxy
 
- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ galaxy_user }}'
    group: '{{ galaxy_user }}'
  with_items:
    - '{{ export_dir }}'
    - '{{ tool_deps_path }}'
    - '{{ galaxy_log_path }}'
    - '{{ galaxy_custom_config_path }}'
    - '{{ custom_utils_path }}'
  become_user: root
  become_method: sudo
