---
# Prerequisites installation recipe

#______________________________________
# CentOS 7

- name: '[EL] Install packages'
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - vim
    - wget
    - lsof
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: '[EL] Install the Development tools package group'
  yum:
    name: "@Development tools"
    state: latest
    skip_broken: yes # This solve broken dependencies on docker indigodatacloud/centos-sshd
    update_cache: yes
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat" and ansible_version.full >= "2.3.0.0"

-  name: '[EL] Install Development tools group' # This solve broken dependencies on docker indigodatacloud/centos-sshd
   command: 'yum groupinstall -y "Development tools" --skip-broken'
   become_user: root
   become_method: sudo
   when: ansible_os_family == "RedHat" and ansible_version.full < "2.3.0.0"

#______________________________________
# Ubuntu

- name: '[Ubuntu] Install packages'
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - vim
    - wget
    - lsof
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

#______________________________________
# Create directories
# WARNING!!! Setup directories after galaxy user creation

- include: path.yml

#______________________________________
- name: 'Clone Galaxy Central Management Tool (galaxyctl)'
  git:
    repo: 'https://github.com/mtangaro/galaxyctl.git'
    clone: yes
    dest: '{{ galaxy_FS_path }}'

- name: Install galaxyctl
  command: 'pip install .'
  args:
    chdir: '{{ galaxy_FS_path }}/galaxyctl'
  become_user: root
  become_method: sudo
