---
- name: '[EL] Install mailutils'
  yum: name={{item}}
       state=present
  with_items:
    - mailx
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: '[Ubuntu] Install mailutils'
  apt: name={{item}}
       state=present
  with_items:
    - mailutils
  become_user: root
  become_method: sudo
  when: ansible_os_family == "Debian"

- name: Send mail using linux mail client
  shell: 'echo "Please ssh into your Galaxy instance: ssh -i <private_key> galaxy@{{ ansible_default_ipv4.address }} and and follow the instructions " | mail -s "{{ mail_subject}}" {{ GALAXY_ADMIN_EMAIL }} -- -f {{ mail_from }}'

- name: Copy indigo-dc.galaxycloud-os scripts
  template:
    src: 'mail.html.j2'
    dest: '/tmp/mail.txt'

- name: Copy instructions file
  copy:
    src: 'instructions.pdf'
    dest: '/tmp/instructions.pdf'

- name: Send mail to alert user. ONLY FOR TESTING, this is not passing gmail antispam filters
  mail:
    from: '{{ mail_from }}'
    to: "{{ GALAXY_ADMIN_EMAIL }}"
    subject: '{{ mail_subject }}'
    body: '{{ lookup("file", "/tmp/mail.txt") }}'
    subtype: html
    attach: /tmp/instructions.pdf
